##
## EPITECH PROJECT, 2021
## my
## File description:
## Makefile
##

SRC = get_input.c \
	my_getnbr.c \
	my_put_nbr.c \
	my_putchar.c \
	my_putstr.c \
	my_show_word_array.c

OBJ = $(SRC:.c=.o)

all:
	gcc -c $(SRC) -I ../include/
	mv $(OBJ) ../
