##
## EPITECH PROJECT, 2021
## my
## File description:
## Makefile
##

SRC = apply_on_matching_nodes.c \
	apply_on_nodes.c \
	rev_list.c \
	sort_list.c

OBJ = $(SRC:.c=.o)

all:
	gcc -c $(SRC) -I ../../include/
	mv $(OBJ) ../../
