##
## EPITECH PROJECT, 2021
## my
## File description:
## Makefile
##

SRC = append_char.c \
	contain.c \
	my_memset.c \
	my_revstr.c \
	my_str_to_word_array.c \
	my_strcat.c \
	my_strcmp.c \
	my_strcpy.c \
	my_strdup.c \
	my_strlen.c \
	my_strncat.c \
	my_strncmp.c \
	my_strncpy.c \
	my_strstr.c \
	replace_str.c

OBJ = $(SRC:.c=.o)

all:
	gcc -c $(SRC) -I ../include/
	mv $(OBJ) ../
