##
## EPITECH PROJECT, 2021
## my
## File description:
## Makefile
##


SRC = my_sort_int_array.c \
	my_sort_word_array.c \
	my_swap.c

OBJ = $(SRC:.c=.o)

all:
	gcc -c $(SRC) -I ../include/
	mv $(OBJ) ../
