##
## EPITECH PROJECT, 2021
## my
## File description:
## Makefile
##

SRC = add_in_sorted_list.c \
	append_node.c \
	concat_list.c \
	delete_nodes.c \
	delete_single_node.c \
	insert_in_list.c \
	merge_lists.c

OBJ = $(SRC:.c=.o)

all:
	gcc -c -g $(SRC) -I ../../include/
	mv $(OBJ) ../../
